/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.Pessoa;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Cadastro_pessoas extends javax.swing.JDialog {


    /**
     * Creates new form Cadastro_pessoas
     */
    public Cadastro_pessoas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Clientes");
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/View/Imagens/Logotipo para loja de açai roxo simples.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        linha_nome = new javax.swing.JLabel();
        linha_CPF = new javax.swing.JLabel();
        linha_data = new javax.swing.JLabel();
        Camp_Nome = new javax.swing.JTextField();
        Camp_CPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Camp_dia = new javax.swing.JTextField();
        Camp_mes = new javax.swing.JTextField();
        Camp_ano = new javax.swing.JTextField();
        Camp_Limpar = new javax.swing.JButton();
        Camp_Cadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Camp_fone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        linha_nome.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        linha_nome.setForeground(new java.awt.Color(102, 0, 102));
        linha_nome.setText("Nome");

        linha_CPF.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        linha_CPF.setForeground(new java.awt.Color(102, 0, 102));
        linha_CPF.setText("CPF");

        linha_data.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        linha_data.setForeground(new java.awt.Color(102, 0, 102));
        linha_data.setText("Data de Nascimento");

        Camp_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_NomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 0, 18)); // NOI18N
        jLabel4.setText("/");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        jLabel5.setText("/");

        Camp_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_diaActionPerformed(evt);
            }
        });

        Camp_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_mesActionPerformed(evt);
            }
        });

        Camp_Limpar.setText("Limpar dados");
        Camp_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_LimparActionPerformed(evt);
            }
        });

        Camp_Cadastrar.setText("Cadastrar");
        Camp_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_CadastrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Telefone");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(linha_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Camp_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(linha_data)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Camp_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Camp_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Camp_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(linha_CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Camp_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Camp_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(Camp_Limpar)
                        .addGap(33, 33, 33)
                        .addComponent(Camp_Cadastrar)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linha_nome)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Camp_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(linha_data)
                        .addComponent(Camp_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(Camp_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(Camp_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linha_CPF)
                    .addComponent(Camp_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Camp_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Camp_Limpar)
                    .addComponent(Camp_Cadastrar))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Camp_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_NomeActionPerformed

    private void Camp_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_mesActionPerformed

    private void Camp_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_diaActionPerformed

    private void Camp_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_LimparActionPerformed
       limpar();    
    }//GEN-LAST:event_Camp_LimparActionPerformed

    private void Camp_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_CadastrarActionPerformed
        String nome = Camp_Nome.getText ();
        String CPF = Camp_CPF.getText();
        String Dia =  Camp_dia.getText();
        String Mes = Camp_mes.getText();
        String Ano = Camp_ano.getText();
        String Fone = Camp_fone.getText();
        String Aniversario = Dia + "/" + Mes + "/" + Ano;
        
        if (nome.isEmpty() || CPF.isEmpty() || Aniversario.isEmpty() || Dia.isEmpty() || Mes.isEmpty() || Ano.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Faltam dados para ser inseridos!", "FALTAM DADOS!", JOptionPane.WARNING_MESSAGE);
        } else {
             boolean isValid = Model.CPF.Validar_cpf(CPF);
            if (isValid == true) {
                System.out.println("O CPF " + CPF + " é válido.");
                 try {
                     Pessoa P = new Pessoa (nome, CPF, Aniversario, Fone );
                     int idade = P.getIdade();
                      if (idade >= 120) {
                    JOptionPane.showMessageDialog(null, "A idade não pode ser maior ou igual a 120 anos!", "Idade Inválida", JOptionPane.ERROR_MESSAGE);
                } else {
                     JOptionPane.showMessageDialog(null, ("Nome: "+P.getNome()+"\nCPF: "+P.getCPF()+"\nData Aniversário: "+P.getAniversario()+"\nIdade: "+P.getIdade()+"\nTelefone: "+P.getTelefone()), "Pessoa Cadastrada no Sistema!", JOptionPane.INFORMATION_MESSAGE);
                     limpar();
                      }
                 } catch (ParseException ex) {
                     Logger.getLogger(Cadastro_pessoas.class.getName()).log(Level.SEVERE, null, ex);
                 }
            } else {
                JOptionPane.showMessageDialog(null, "CPF é invalido!", "Dado incorreto!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Camp_CadastrarActionPerformed
        private void limpar(){
        Camp_Nome.setText("");
        Camp_CPF.setText("");
        Camp_dia.setText("");
        Camp_mes.setText("");
        Camp_ano.setText("");    
        Camp_fone.setText("");
        }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_pessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro_pessoas dialog = new Cadastro_pessoas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Camp_CPF;
    private javax.swing.JButton Camp_Cadastrar;
    private javax.swing.JButton Camp_Limpar;
    private javax.swing.JTextField Camp_Nome;
    private javax.swing.JTextField Camp_ano;
    private javax.swing.JTextField Camp_dia;
    private javax.swing.JTextField Camp_fone;
    private javax.swing.JTextField Camp_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel linha_CPF;
    private javax.swing.JLabel linha_data;
    private javax.swing.JLabel linha_nome;
    // End of variables declaration//GEN-END:variables

}
