/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Interface_01_1 extends javax.swing.JFrame {
    
    private final String Super_Usuario = "admin";
    private final String Super_Senha = "admin123";
    
    public Interface_01_1() {
        initComponents();
        setTitle("Sistema de Login ");
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/View/Imagens/Logotipo para loja de açai roxo simples.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        TextUsuario = new javax.swing.JLabel();
        TextSenha = new javax.swing.JLabel();
        Camp_Usuario = new javax.swing.JTextField();
        Camp_Senha = new javax.swing.JPasswordField();
        BotLogar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TextUsuario.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        TextUsuario.setForeground(new java.awt.Color(102, 0, 102));
        TextUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextUsuario.setText("Usuário");
        TextUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TextSenha.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        TextSenha.setForeground(new java.awt.Color(102, 0, 102));
        TextSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextSenha.setText("Senha");
        TextSenha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Camp_Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Camp_Usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Camp_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_UsuarioActionPerformed(evt);
            }
        });

        Camp_Senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Camp_Senha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Camp_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Camp_SenhaActionPerformed(evt);
            }
        });

        BotLogar.setBackground(new java.awt.Color(153, 153, 153));
        BotLogar.setText("Logar");
        BotLogar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        BotLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotLogarActionPerformed(evt);
            }
        });
        BotLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BotLogarKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Logotipo para loja de açai roxo simples.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(BotLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Camp_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Camp_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(TextUsuario)
                .addGap(18, 18, 18)
                .addComponent(Camp_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Camp_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotLogar)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Camp_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_UsuarioActionPerformed

    private void Camp_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Camp_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Camp_SenhaActionPerformed

    private void BotLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotLogarActionPerformed
        Logar();
        Limpar();
    }//GEN-LAST:event_BotLogarActionPerformed

    private void BotLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BotLogarKeyPressed
       Logar();
       Limpar();
    }//GEN-LAST:event_BotLogarKeyPressed

    private void Logar(){
        String Usuario = Camp_Usuario.getText();
    String Senha = Camp_Senha.getText();
    
    if(Usuario.isEmpty()||Senha.isEmpty()){
        JOptionPane.showMessageDialog(null, "Preciso do Usuário e Senha!" , "Faltam Dados", JOptionPane.WARNING_MESSAGE);
    } else if (Usuario.equals(Super_Usuario)&& Senha.equals(Super_Senha)){
        Cadastro_pessoas Nova_tela = new Cadastro_pessoas(new javax.swing.JFrame(), true);
        Nova_tela.setVisible(true);
   } else {
        JOptionPane.showMessageDialog(null, "Usuário INVÁLIDO!", "ERRO de LOGIN!", JOptionPane.ERROR_MESSAGE);

    }
       
    }
    private void Limpar(){
         Camp_Usuario.setText("");
        Camp_Senha.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface_01_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface_01_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface_01_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface_01_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface_01_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotLogar;
    private javax.swing.JPasswordField Camp_Senha;
    private javax.swing.JTextField Camp_Usuario;
    private javax.swing.JLabel TextSenha;
    private javax.swing.JLabel TextUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
